### ISSUE TITLE
How exactly does it download the specific Magento-Version

### ISSUE THREAD

**Issue by azngeek** [AOEpeople/MageTestStand#2]
I took a look into the code but was not able to found the code where composer downloads the specific magento version

```
  Magento Installation


  - Installing magento-ce-1.9.0.1 (1.9.0.1)
    Downloading: 100%

```

Where is this part? ...

**Comment by fbrnc** [comment]
Hi,
MageTestStand uses n98-magerun to install Magento.
Here's where the magic happens:
https://github.com/AOEpeople/MageTestStand/blob/174468d7a1adc69d27bd560b831bc579ffd665ed/install.sh#L41-47

Cheers,
Fabrizio

**Comment by azngeek** [comment]
Ahh i see. I thought of that but did miss that line. Thanks for the hint. 

best regards
