### ISSUE TITLE
How do I use the skipCleanUp command

### ISSUE THREAD

**Issue by jg-development** [AOEpeople/MageTestStand#3]
Hi,

I think the topic speaks for itself ;-)
Maybe an update of the README.md would be nice

Greetings Jan

**Comment by jg-development** [comment]
I mean without the export function ... is there another option?

**Comment by fbrnc** [comment]
Hi, there's no command line parameter that will set this. 
When using Travis CI you can configure it like this: https://github.com/AOEpeople/Aoe_Scheduler/blob/master/.travis.yml#L15

Will this work for you or what are you trying to do?

**Comment by fbrnc** [comment]
I've added some content to the readme file too.

**Comment by jg-development** [comment]
Hi,
this will work for me.... thanks
Jan
