### ISSUE TITLE
Databases with dashes will result in an error

### ISSUE THREAD

**Issue by azngeek** [AOEpeople/MageTestStand#6]
When you have a database name like db-1 this will result in an error. Can this be solved by escaping the variables? I am not that familiar with bash scripting.

**Comment by fbrnc** [comment]
Can you test if your problem is fixed now (I'm also testing this right now. Waiting for a travis build to complete...)

**Comment by azngeek** [comment]
Okay, i need to change some jenkins configs first. I will let you know. 

Update:

Looks good now. Thanks :+1:
