### ISSUE TITLE
Cannot recognise unit tests

### ISSUE THREAD

**Issue by robbieaverill** [AOEpeople/MageTestStand#9]
Hi,

My set up is:
- I have a light Magento module with a modman file attached
- I added your example Travis YAML configuration file
- I've changed the Magento version name to magento-mirror to avoid the "cannot resolve Magento version" error in Magerun
- When I build, everything goes as planned except I get "No tests executed"

I can't seem to get the EcomDev PHPUnit configuration file to fire with the example provided. Any advice?

Cheers,
Robbie

**Comment by fbrnc** [comment]
Hi @robbieaverill,
currently there's this "multi-level" mess happening (and I think we're close to having this resolved now:
- Magento.com doesn't allow easily downloading the Magento sources
- Installing magento-ce-\* stopped working in n98-magerun
- Instead you could use magento-mirror-*
- Some magento-mirror-\* versions were missing in n98-magerun
- Some Magento versions weren't tagged in OpenMage/magento-mirror.

Not sure if this has anything to do with your problem.
Are you using Travis CI? Can you point me to the build that's failing? And/or to the Magento module you're trying to test?

**Comment by robbieaverill** [comment]
Hey @fbrnc 

Thanks for getting back to me. It looks like using the mirror is working to install Magento, just not picking up any unit tests.

An example of the latest build using this module's standard configuration (with all the other PHP versions and Magento versions commented out) is here: https://travis-ci.org/robbieaverill/magento-attribute-option-order-fix/builds/90030542

The build configuration I'm using is here: https://github.com/robbieaverill/magento-attribute-option-order-fix/blob/feature/4-add-unit-tests/.travis.yml - you can see the unit tests I've added in that branch under `app/code/local/RobbieAverill/AttributeFix/Test` - here: https://github.com/robbieaverill/magento-attribute-option-order-fix/tree/feature/4-add-unit-tests/app/code/local/RobbieAverill/AttributeFix/Test

Thanks!

Robbie

**Comment by robbieaverill** [comment]
Maybe this is an issue with the fact that modman has symlinked it? Just testing it locally it won't pick up the module when I run `phpunit --list-groups` or `phpunit --group RobbieAverill_AttributeFix` from the root directory, however it will if I run `phpunit app/code/local/RobbieAverill/AttributeFix/Test`.

Issue documented here: https://github.com/sebastianbergmann/phpunit/issues/217

**Comment by robbieaverill** [comment]
Hi again @fbrnc 

Sorry to waste your time. It turned out that I had lost the PHPUnit declaration in config.xml somewhere along the line. I've committed it back in and the build is running successfully now: https://travis-ci.org/robbieaverill/magento-attribute-option-order-fix

Cheers.
Robbie

**Comment by fbrnc** [comment]
Nice! I'm glad it's working now.
